
  name: Build
  on: 
    push:
      branches:
        - main
  jobs:
    deploy:
      runs-on: ubuntu-latest
      permissions:
        pages: write
        id-token: write
      env:
        LastArtiFact: onepisya-github-pages-1692557465484
        built: false
      environment:
        name: onepisya-github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      # 缓存 
      steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
  
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
            npm install -g pnpm
            pnpm install
      # ============ 脚本自动生成 ==============   
      - uses: tj-actions/changed-files@v35
        id: changed-2022-12-10
        # 文件修改检测
        with:
          files: |
            2022-12-10/src/*
      - name: Build 2022-12-10
        if: steps.changed-2022-12-10.outputs.any_changed == 'true'
        run: |
          pnpm -C 2022-12-10/src run build
          echo "built=true" >> $GITHUB_ENV
      - name: Debug
        run: |
          echo "any_changed: ${{ steps.changed-2022-12-10.outputs.any_changed }}"
        
   
      - uses: tj-actions/changed-files@v35
        id: changed-2023-05-17
        # 文件修改检测
        with:
          files: |
            2023-05-17/src/*
      - name: Build 2023-05-17
        if: steps.changed-2023-05-17.outputs.any_changed == 'true'
        run: |
          pnpm -C 2023-05-17/src run build
          echo "built=true" >> $GITHUB_ENV
      - name: Debug
        run: |
          echo "any_changed: ${{ steps.changed-2023-05-17.outputs.any_changed }}"
        
      # ============ 生成结束 ==============
      - name: Upload artifact
        if: ${{env.built}} == true
        id: upload
        uses: actions/upload-pages-artifact@v1
        with:
          name: onepisya-github-pages-1692563531687
          path: dist/

      - name: Debug
        run: |
          echo "built: ${{env.built}}"
      - name: Deploy to GitHub Pages
        if: ${{env.built}} == true
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: onepisya-github-pages-1692563531687
      - name: show messages
        run: |
          echo ${{ steps.deployment.outputs.page_url }}
  