name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    # 缓存 
    steps:
    - uses: actions/checkout@v2

    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - name: Install dependencies
      run: pnpm install

    - uses: tj-actions/changed-files@v35
      id: changed
    # 下面这些就是需要用脚本生成的内容
    - name: Build 2022-12-10
      if: steps.changed.outputs.any_changed == 'true'
      run: pnpm -C 2022-12-10/src run build
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
       name: github-pages
       path: ../../dist/2022/vueuse-best-practice