name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    # 缓存 
    steps:
    - uses: actions/checkout@v2

    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
          npm install -g pnpm
          pnpm install

    - uses: tj-actions/changed-files@v35
      id: changed
      # 文件修改检测
      # 2022-12-10/src/*
      with:
        files: |
          **/src/*
    # 下面这些就是需要用脚本生成的内容
    - name: Build 2022-12-10
      if: steps.changed.outputs.any_changed == 'true'
      run: pnpm -C 2022-12-10/src run build
    - name: Build 2023-05-17
      if: steps.changed.outputs.any_changed == 'true'
      run: pnpm -C 2023-05-17/src run build
    - name: Debug
      run: |
        echo "any_changed: ${{ steps.changed.outputs.any_changed }}"
        ls -la 2022-12-10/src
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
       name: github-pages
       path: dist/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
      - name: show messages
        run: |
          echo ${{ steps.deployment.outputs.page_url }}