
  name: Build
  on: 
    push:
      branches:
        - main
  jobs:
    build:
      runs-on: ubuntu-latest
      permissions:
        pages: write
        id-token: write
      environment:
        name: onepisya-github-pages
      env:
        LastArtiFact: onepisya-github-pages-1692564433922
      # 缓存 
      steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
  
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
            npm install -g pnpm
            pnpm install
      # ============ 脚本自动生成 ==============   
      - uses: tj-actions/changed-files@v35
        id: changed-2022-12-10
        # 文件修改检测
        with:
          files: |
            2022-12-10/src/*
      - name: Build 2022-12-10
        if: steps.changed-2022-12-10.outputs.any_changed == 'true'
        run: pnpm -C 2022-12-10/src run build
      - name: Debug
        run: |
          echo "any_changed: ${{ steps.changed-2022-12-10.outputs.any_changed }}"
        
   
      - uses: tj-actions/changed-files@v35
        id: changed-2023-05-17
        # 文件修改检测
        with:
          files: |
            2023-05-17/src/*
      - name: Build 2023-05-17
        if: steps.changed-2023-05-17.outputs.any_changed == 'true'
        run: pnpm -C 2023-05-17/src run build
      - name: Debug
        run: |
          echo "any_changed: ${{ steps.changed-2023-05-17.outputs.any_changed }}"
        
   
      - uses: tj-actions/changed-files@v35
        id: changed-2023-08-22
        # 文件修改检测
        with:
          files: |
            2023-08-22/src/*
      - name: Build 2023-08-22
        if: steps.changed-2023-08-22.outputs.any_changed == 'true'
        run: pnpm -C 2023-08-22/src run build
      - name: Debug
        run: |
          echo "any_changed: ${{ steps.changed-2023-08-22.outputs.any_changed }}"
        
   
      - uses: tj-actions/changed-files@v35
        id: changed-2023-08-23
        # 文件修改检测
        with:
          files: |
            2023-08-23/src/*
      - name: Build 2023-08-23
        if: steps.changed-2023-08-23.outputs.any_changed == 'true'
        run: pnpm -C 2023-08-23/src run build
      - name: Debug
        run: |
          echo "any_changed: ${{ steps.changed-2023-08-23.outputs.any_changed }}"
        
      # ============ 生成结束 ==============
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1 
        # have not skipped, but it is designed to fail if there is no artifact to upload
        with:
          name: onepisya-github-pages-1692714523496
          path: dist/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.3 # tag: Better
        with:
          publish_branch: gh-pages  # default: gh-pages
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./dist
          allow_empty_commit: true
          keep_files: true
          # force_orphan: true
  